name: End-to-End Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies 📦
        # we could simply run "npm ci" but that would not cache dependencies
        # thus we can use this 3rd party action
        uses: bahmutov/npm-install@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm run dev
          wait-on: http://localhost:3000